# ANSIBLE ENV
ansible_connection: ssh
ansible_user: 
ansible_ssh_pass: 
ansible_sudo_pass: 
ansible_ssh_private_key_file: files/secrets/ssh.key
ansible_python_interpreter: /usr/bin/python3

# SSH ENV
pass_auth: PasswordAuthentication yes
pubkey_auth: PubkeyAuthentication yes

# SWAP ENV
swap_file_path: /swapfile
swap_file_size: 2048
swappiness: 1

# DOCKER ENV
docker_apt_release_channel: stable
docker_apt_arch: amd64
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_apt_gpg_key: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg


# FIREWALL ENV
ufw_rule: allow

# DOMAIN ENV
elio_domain: servermanajer.com
elio_sub_domain: wordpress.user6.servermanajer.com
elio_sub_domain_ip: 13.229.235.168

# MYSQL ENV
mysql_docker_name: mysql
mysql_docker_image: mysql
mysql_docker_tag: latest
mysql_docker_ports: 3306
mysql_docker_env_root_password: mysql-root-pass # default user is a root
mysql_docker_env_database: mysql-db-test # create a new database
mysql_docker_env_user: mysql-user-test # create a new user
mysql_docker_env_password: mysql-pass-test # create a new password

# MARIADB ENV
mariadb_docker_name: mariadb
mariadb_docker_image: mariadb
mariadb_docker_tag: latest
mariadb_docker_ports: 3306
mariadb_docker_env_root_password: mariadb-root-pass # default user is a root
mariadb_docker_env_database: mariadb-db-test # create a new database
mariadb_docker_env_user: mariadb-user-test # create a new user
mariadb_docker_env_password: mariadb-pass-test # create a new password


# POSTGRES ENV
postgresql_docker_name: postgresql
postgresql_docker_image: postgres
postgresql_docker_tag: 13-bullseye
postgresql_docker_ports: 5432
postgresql_docker_env_root_password: postgresql-root-pass
postgresql_docker_env_database: postgresql-db-test
postgresql_docker_env_user: postgresql-user-test
postgresql_docker_env_password: postgresql-pass-test

# PGADMIN ENV
pgadmin_docker_name: pgadmin
pgadmin_docker_image: dpage/pgadmin4
pgadmin_docker_tag: latest
pgadmin_docker_ports: 15432
pgadmin_docker_env_default_email: admin@elio.com
pgadmin_docker_env_default_password: elio

# MONGODB ENV
mongodb_docker_name: mongodb
mongodb_docker_image: mongodb
mongodb_docker_tag: latest
mongodb_docker_ports: 27017
mongodb_docker_env_root_username: mongodb-root-user # default user is a root
mongodb_docker_env_root_password: mongodb-root-pass # default user is a root


# JENKINS ENV
jenkins_docker_name: jenkins
jenkins_docker_iamge: jenkins
jenkins_docker_tag: 2.60.3-alpine
jenkins_docker_ui_ports: 8081
jenkins_docker_slave_ports: 50001


# REDIS ENV
redis_docker_name: redis
redis_docker_image: redis
redis_docker_tag: latest
redis_docker_ports: 6379
redis_docker_env_password: redis-password
