# elio - PostgreSQL Install
- name: "Install PostgreSQL Database"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ postgresql_docker_name }}"
    image: "{{ postgresql_docker_image }}:{{ postgresql_docker_tag }}"
    networks:
      - name: elio-network
    restart_policy: always
    ports:
      - "{{ postgresql_docker_ports }}:5432"
    env:
      POSTGRES_ROOT_PASSWORD: "{{ postgresql_docker_env_root_password }}"
      POSTGRES_DATABASE: "{{ postgresql_docker_env_database }}"
      POSTGRES_USER: "{{ postgresql_docker_env_user }}"
      POSTGRES_PASSWORD: "{{ postgresql_docker_env_password }}"
    volumes:
      - "/elio/{{ postgresql_docker_name }}-data:/var/lib/postgresql/data"
  tags:
    - install-postgresql

# elio - PostgreSQL Firewall Install
- name: "'{{ ufw_rule }}' port '{{ postgresql_docker_ports }}'"
  community.general.ufw:
    rule: "{{ ufw_rule }}"
    port: "{{ item }}"
    proto: tcp
  loop:
    - "{{ postgresql_docker_ports | quote }}"
  tags:
    - install-postgresql

# elio - PostgreSQL Uninstall    
- name: "Remove PostgreSQL Database"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ postgresql_docker_name }}"
    state: absent
  tags:
    - uninstall-postgresql

# elio - PostgreSQL Firewall Uninstall
- name: "'{{ ufw_rule }}' port '{{ postgresql_docker_ports }}'"
  community.general.ufw:
    rule: "{{ ufw_rule }}"
    port: "{{ item }}"
    proto: tcp
    delete: yes
  loop:
    - "{{ postgresql_docker_ports | quote }}"
  tags:
    - uninstall-postgresql

# elio - PostgreSQL Uninstall with Data
- name: "uninstall postgresql data"
  become_user: "{{ ansible_user }}"
  shell: "sudo rm -fr /elio/{{ postgresql_docker_name }}-data"
  tags:
    - uninstall-postgresql-data