# elio - MySQL Install
- name: "install mysql"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ mysql_docker_name }}"
    image: "{{ mysql_docker_image }}:{{ mysql_docker_tag }}"
    networks:
      - name: elio-network
    volumes:
      - "/elio/{{ mysql_docker_name }}-data:/var/lib/mysql"
    restart_policy: always
    ports:
      - "{{ mysql_docker_ports }}:3306"
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_docker_env_root_password }}"
      MYSQL_DATABASE: "{{ mysql_docker_env_database }}"
      MYSQL_USER: "{{ mysql_docker_env_user }}"
      MYSQL_PASSWORD: "{{ mysql_docker_env_password }}"
  tags:
    - install-mysql

# elio - MySQL Firewall Install
- name: "'{{ ufw_rule }}' port '{{ mysql_docker_ports }}'"
  community.general.ufw:
    rule: "{{ ufw_rule }}"
    port: "{{ item }}"
    proto: tcp
  loop:
    - "{{ mysql_docker_ports | quote }}"
  tags:
    - install-mysql

# elio - MySQL Uninstall
- name: "uninstall mysql"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ mysql_docker_name }}"
    state: absent
  tags:
    - uninstall-mysql

# elio - MySQL Firewall Uninstall
- name: "'{{ ufw_rule }}' port '{{ mysql_docker_ports }}'"
  community.general.ufw:
    rule: "{{ ufw_rule }}"
    port: "{{ item }}"
    proto: tcp
    delete: yes
  loop:
    - "{{ mysql_docker_ports | quote }}"
  tags:
    - uninstall-mysql

# elio - MySQL Uninstall with Data
- name: "uninstall mysql data"
  become_user: "{{ ansible_user }}"
  shell: "sudo rm -fr /elio/{{ mysql_docker_name }}-data"
  tags:
    - uninstall-mysql-data